name: Sync fork with upstream

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream into default branch
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          set -euo pipefail
          curl -sS -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${REPO}/merge-upstream" \
            -d "{\"branch\":\"${BRANCH}\"}"
